### ISSUE TITLE
What's the sql migratin files

### ISSUE THREAD

**Issue by Em4g3** [g1-1-1/goodblox#2]

**Comment by genosmrpg7899** [comment]
40.744308°N 73.996396°W

**Comment by Em4g3** [comment]
?

**Comment by genosmrpg7899** [comment]
The SQL migration files can be found in that location

**Comment by Em4g3** [comment]
...

**Comment by g1-1-1** [comment]
make them yourself
if you can't make them yourself, then you don't need to be messing with this
